### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by oliversalzburg**
The package name `languagelist` is available on the npm registry.

Would be nice to have this great data easily available in Node projects :)

### CODE REVIEW

**Comment by umpirsky** [comment]
It's a lot of data for a npm package, but ok. :)

**Comment by oliversalzburg** [comment]
Heh, indeed. Haven't though about that. I wonder what the size limit is for npm packages...

**Comment by umpirsky** [comment]
No clue, if there is one at all. But I would think twice before I include this in my project. Maybe we should add some warning?

**Comment by oliversalzburg** [comment]
Seems like there is [no hard limit](https://github.com/npm/npm/issues/12750). I personally wanted to include this in a project to seed a database programatically. Size would not be relevant for us.

The gzipped tarball is "only" 24 MB. I wouldn't include it in a frontend project, but for the backend, I like it ;D

**Comment by lazarljubenovic** [comment]
So now we have `package.json` but no published npm module (the name is still free)? :crying_cat_face: I have the same use-case: need this for seeding a languages table in a database.

**Comment by oliversalzburg** [comment]
@lazarljubenovic A published package would be nice, but you can also just declare `umpirsky/language-list` as the dependency version and it will be pulled from GitHub.

**Pull request merged**
